# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: release

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Get tag
        id: get_tag
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Checkout repository
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
        with:
          ref: ${{ steps.get_tag.outputs.VERSION }}

      - name: Setup Node
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org
          cache: yarn

      - name: Get npm version
        id: npm-tag
        uses: martinbeentjes/npm-get-version-action@3cf273023a0dda27efcd3164bdfb51908dd46a5b # v1.3.1

      - name: Output tags
        run: echo GIT ${{ github.ref_name }} NPM ${{ steps.npm-tag.outputs.current-version }}

      - name: Check if tag and npm version match
        if: ${{ github.ref_name != steps.npm-tag.outputs.current-version }}
        run: echo "version not matching" && exit 1 
  
      - name: Versions match
        if: ${{ github.ref_name == steps.npm-tag.outputs.current-version }}
        run: echo "tag and npm version match"

      - name: Install Dependencies
        run: yarn

      - name: Linter Checks
        run: yarn lint

      - name: Unit Tests
        run: CI=true yarn test

      - name: Build Library
        run: yarn build

      - name: Build Sample App
        run: yarn build:sample

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'build'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Publish Shared Components to npm
        run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH }}
